export { ClaudeBrowser } from './browser.js';
export {
  createFavicon,
  convert,
  resize,
  crop,
  compress,
  thumbnail,
  type FaviconResult,
  type ImageResult,
  type FitType,
  type FormatType,
  type ThumbnailSize,
} from './image.js';
export type {
  BrowserOptions,
  BrowserCommand,
  CommandResponse,
  ElementInfo,
  SuccessResponse,
  ErrorResponse,
  GotoCommand,
  ClickCommand,
  TypeCommand,
  QueryCommand,
  ScreenshotCommand,
  UrlCommand,
  HtmlCommand,
  BackCommand,
  ForwardCommand,
  ReloadCommand,
  WaitCommand,
  NewPageCommand,
  CloseCommand,
  EvalCommand,
  FaviconCommand,
  ConvertCommand,
  ResizeCommand,
  CropCommand,
  CompressCommand,
  ThumbnailCommand,
} from './types.js';
